[package]
name = "polynomial"
version = "0.1.0"
authors = ["Matthew Torrence <matt@torrencefamily.net>"]
edition = "2018"

[dependencies]
# TODO: This dependency will become a not path dependency before release
nt_traits = { path = "../traits" }
num-traits = "0.2"
alga = "0.9.3"
