[package]
name = "finite_field"
version = "0.1.0"
authors = ["Matthew Torrence <matt@torrencefamily.net>"]
edition = "2018"

[dependencies]
num-traits = "0.2"
alga = "0.9.3"
nt_polynomial = { path = "../polynomial" }
nt_traits = { path = "../traits" }
